// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryUseCase is an autogenerated mock type for the RepositoryUseCase type
type RepositoryUseCase struct {
	mock.Mock
}

// CheckForUpdates provides a mock function with given fields: ctx, repo
func (_m *RepositoryUseCase) CheckForUpdates(ctx context.Context, repo model.Repository) (*model.Repository, error) {
	ret := _m.Called(ctx, repo)

	if len(ret) == 0 {
		panic("no return value specified for CheckForUpdates")
	}

	var r0 *model.Repository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Repository) (*model.Repository, error)); ok {
		return rf(ctx, repo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Repository) *model.Repository); ok {
		r0 = rf(ctx, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Repository) error); ok {
		r1 = rf(ctx, repo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrCreate provides a mock function with given fields: ctx, repoName
func (_m *RepositoryUseCase) GetOrCreate(ctx context.Context, repoName string) (*model.Repository, error) {
	ret := _m.Called(ctx, repoName)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *model.Repository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Repository, error)); ok {
		return rf(ctx, repoName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Repository); ok {
		r0 = rf(ctx, repoName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repoName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepositoryUseCase creates a new instance of RepositoryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryUseCase {
	mock := &RepositoryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
