// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// SubscriptionWriter is an autogenerated mock type for the SubscriptionWriter type
type SubscriptionWriter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, userID, repoName
func (_m *SubscriptionWriter) Delete(ctx context.Context, userID int64, repoName string) error {
	ret := _m.Called(ctx, userID, repoName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, repoName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, sub
func (_m *SubscriptionWriter) Save(ctx context.Context, sub *model.Subscription) error {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Subscription) error); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSubscriptionWriter creates a new instance of SubscriptionWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionWriter {
	mock := &SubscriptionWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
