// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// SubscriptionReader is an autogenerated mock type for the SubscriptionReader type
type SubscriptionReader struct {
	mock.Mock
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *SubscriptionReader) GetByEmail(ctx context.Context, email string) ([]model.Subscription, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 []model.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Subscription, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Subscription); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByRepoID provides a mock function with given fields: ctx, repoID
func (_m *SubscriptionReader) GetByRepoID(ctx context.Context, repoID int64) ([]model.Subscriber, error) {
	ret := _m.Called(ctx, repoID)

	if len(ret) == 0 {
		panic("no return value specified for GetByRepoID")
	}

	var r0 []model.Subscriber
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Subscriber, error)); ok {
		return rf(ctx, repoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Subscriber); ok {
		r0 = rf(ctx, repoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscriber)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, repoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByToken provides a mock function with given fields: ctx, token
func (_m *SubscriptionReader) GetByToken(ctx context.Context, token string) (*model.Subscription, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetByToken")
	}

	var r0 *model.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSubscriptionReader creates a new instance of SubscriptionReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionReader {
	mock := &SubscriptionReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
