FROM golang:1.26-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o bin/notification_worker ./cmd/notification-worker/


FROM alpine:3.18

WORKDIR /app
COPY --from=builder /app/bin/notification_worker .

CMD ["./notification_worker"]
