// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	contracts "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/contracts"
	mock "github.com/stretchr/testify/mock"
)

// NotificationUseCase is an autogenerated mock type for the NotificationUseCase type
type NotificationUseCase struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, cmd
func (_m *NotificationUseCase) Send(ctx context.Context, cmd contracts.SendNotificationCommand) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.SendNotificationCommand) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendConfirmation provides a mock function with given fields: ctx, cmd
func (_m *NotificationUseCase) SendConfirmation(ctx context.Context, cmd contracts.SendConfirmationCommand) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for SendConfirmation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.SendConfirmationCommand) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationUseCase creates a new instance of NotificationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationUseCase {
	mock := &NotificationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
