apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-subscription
spec:
  serviceName: postgres-subscription
  replicas: 1
  selector:
    matchLabels:
      app: postgres-subscription
  template:
    metadata:
      labels:
        app: postgres-subscription
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - configMapRef:
                name: postgres-subscription-config
            - secretRef:
                name: postgres-subscription-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "ReilYehor", "-d", "subscription_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi