apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-config
data:
  TRACKING_DB_MAX_OPEN_CONNS: "25"
  TRACKING_DB_MIN_CONNS: "5"
  TRACKING_DB_MAX_CONN_IDLE_TIME: "30m"
  TRACKING_DB_HEALTH_CHECK_PERIOD: "1m"
  TRACKING_GRPC_PORT: "50051"
  APP_BASE_URL: "http://localhost:8080"
  RATE_LIMIT: "10-S"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  GITHUB_HTTP_TIMEOUT: "10s"
  GITHUB_CB_MAX_REQUESTS: "3"
  GITHUB_CB_INTERVAL: "5s"
  GITHUB_CB_TIMEOUT: "30s"
  GITHUB_CB_FAILURE_THRESHOLD: "3"
  NOTIFICATION_INTERVAL: "1m"
  WORKER_MAX_SEND_WORKERS: "10"
  WORKER_HEALTH_PORT: "8081"
  TAG_PUBLISHER_TYPE: "grpc"
  SUBSCRIPTION_GRPC_ADDR: "subscription:9091"
