apiVersion: v1
kind: Secret
metadata:
  name: tracking-secret
type: Opaque
stringData:
  TRACKING_DB_SOURCE: "postgres://ReilYehor:ReilYehor159951@postgres-tracking:5432/tracker_db?sslmode=disable"
  REDIS_PASSWORD: "ReilYehor159951"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  APP_API_KEY: "my-super-secret-token-123"
  GITHUB_TOKEN: ""
