// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	"time"

	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/subscription/internal/infrastructure/adapter"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/subscription/internal/infrastructure/outbox"
	postgres3 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/subscription/internal/repository/postgres"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/subscription/internal/saga"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/subscription/internal/transport/broker/rabbitmq"
	grpc3 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/subscription/internal/transport/grpc"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/subscription/internal/transport/http"
	usecase2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/subscription/internal/usecase"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/config"
	rabbitmq2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/infrastructure/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/infrastructure/cache/redis"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/infrastructure/grpc/proto/v1"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/infrastructure/storage/postgres"
	grpc2 "google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg Config) (*App, func(), error) {
	subscriptionDBConfig := ProvideSubscriptionDBConfig(cfg)
	poolConfig := ProvideSubscriptionPoolConfig(subscriptionDBConfig)
	pool, cleanup, err := postgres.New(ctx, poolConfig)
	if err != nil {
		return nil, nil, err
	}
	subscriptionRepository := postgres3.NewSubscriptionRepository(pool)
	userRepository := postgres3.NewUserRepository(pool)
	trackingClientConfig := ProvideTrackingClientConfig(cfg)
	clientConn, cleanup2, err := ProvideTrackingGRPCConn(trackingClientConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	trackingServiceClient := ProvideTrackingServiceClient(clientConn)
	repositoryRepository := postgres3.NewRepositoryRepository(pool)
	repositoryUseCaseAdapter := adapter.NewRepositoryUseCaseAdapter(trackingServiceClient, repositoryRepository, trackingClientConfig)
	sagaRepository := postgres3.NewSagaRepository(pool)
	outboxRepository := postgres3.NewOutboxRepository(pool)
	transactor := postgres.NewTransactor(pool)
	orchestrator := saga.NewOrchestrator(sagaRepository, subscriptionRepository, outboxRepository, transactor)
	userUseCase, cleanup3 := usecase2.NewUserUseCase(ctx, subscriptionRepository, userRepository, repositoryUseCaseAdapter, orchestrator, transactor, outboxRepository)
	repositoryUseCase := usecase2.NewRepositoryUseCase(repositoryRepository)
	redisConfig := ProvideRedisConfig(cfg)
	client, err := redis.NewRedisClient(redisConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpConfig := ProvideHTTPConfig(cfg)
	appConfig := ProvideAppConfig(cfg)
	ginServer := http.NewGinServer(userUseCase, repositoryUseCase, client, httpConfig, appConfig)
	subscriptionHandler := grpc3.NewSubscriptionHandler(userUseCase, repositoryUseCase)
	server := grpc3.NewGrpcServer(subscriptionHandler, appConfig)
	rabbitMQConfig := ProvideRabbitMQConfig(cfg)
	connection, cleanup4, err := ProvideRabbitMQConnection(rabbitMQConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sagaResultConsumer := rabbitmq.NewSagaResultConsumer(connection, orchestrator)
	duration := ProvideOutboxInterval()
	relay := outbox.NewRelay(outboxRepository, connection, duration)
	app := &App{
		HTTPServer:         ginServer,
		GrpcServer:         server,
		SagaResultConsumer: sagaResultConsumer,
		OutboxRelay:        relay,
	}
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func ProvideSubscriptionDBConfig(cfg Config) config.SubscriptionDBConfig { return cfg.SubscriptionDB }

func ProvideRedisConfig(cfg Config) config.RedisConfig { return cfg.Redis }

func ProvideHTTPConfig(cfg Config) config.HTTPConfig { return cfg.HTTP }

func ProvideAppConfig(cfg Config) config.AppConfig { return cfg.App }

func ProvideRabbitMQConfig(cfg Config) config.RabbitMQConfig { return cfg.RabbitMQ }

func ProvideTrackingClientConfig(cfg Config) config.TrackingClientConfig { return cfg.TrackingClient }

func ProvideRabbitMQConnection(cfg config.RabbitMQConfig) (*rabbitmq2.Connection, func(), error) {
	return rabbitmq2.NewConnection(cfg.URL)
}

func ProvideOutboxInterval() time.Duration {
	return 5 * time.Second
}

func ProvideTrackingGRPCConn(cfg config.TrackingClientConfig) (*grpc2.ClientConn, func(), error) {
	conn, err := grpc2.NewClient(cfg.TrackingGRPCAddr, grpc2.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, nil, fmt.Errorf("dial tracking grpc: %w", err)
	}
	return conn, func() { conn.Close() }, nil
}

func ProvideTrackingServiceClient(conn *grpc2.ClientConn) v1.TrackingServiceClient {
	return v1.NewTrackingServiceClient(conn)
}

type App struct {
	HTTPServer         *http.GinServer
	GrpcServer         *grpc2.Server
	SagaResultConsumer *rabbitmq.SagaResultConsumer
	OutboxRelay        *outbox.Relay
}
