// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// SagaRepository is an autogenerated mock type for the SagaRepository type
type SagaRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, subscriptionID
func (_m *SagaRepository) Create(ctx context.Context, subscriptionID int64) (*model.SubscriptionSaga, error) {
	ret := _m.Called(ctx, subscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.SubscriptionSaga
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SubscriptionSaga, error)); ok {
		return rf(ctx, subscriptionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SubscriptionSaga); ok {
		r0 = rf(ctx, subscriptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SubscriptionSaga)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, subscriptionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, sagaID, status
func (_m *SagaRepository) UpdateStatus(ctx context.Context, sagaID int64, status model.SagaStatus) error {
	ret := _m.Called(ctx, sagaID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, model.SagaStatus) error); ok {
		r0 = rf(ctx, sagaID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusAndStep provides a mock function with given fields: ctx, sagaID, status, step
func (_m *SagaRepository) UpdateStatusAndStep(ctx context.Context, sagaID int64, status model.SagaStatus, step model.SagaStep) error {
	ret := _m.Called(ctx, sagaID, status, step)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusAndStep")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, model.SagaStatus, model.SagaStep) error); ok {
		r0 = rf(ctx, sagaID, status, step)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSagaRepository creates a new instance of SagaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSagaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SagaRepository {
	mock := &SagaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
