// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	contracts "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/contracts"
	mock "github.com/stretchr/testify/mock"
)

// TagUpdatedPublisher is an autogenerated mock type for the TagUpdatedPublisher type
type TagUpdatedPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, event
func (_m *TagUpdatedPublisher) Publish(ctx context.Context, event contracts.TagUpdatedEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.TagUpdatedEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTagUpdatedPublisher creates a new instance of TagUpdatedPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagUpdatedPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagUpdatedPublisher {
	mock := &TagUpdatedPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
