// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TrackerSubscriptionWriter is an autogenerated mock type for the TrackerSubscriptionWriter type
type TrackerSubscriptionWriter struct {
	mock.Mock
}

// Upsert provides a mock function with given fields: ctx, repoID, email, token
func (_m *TrackerSubscriptionWriter) Upsert(ctx context.Context, repoID int64, email string, token string) error {
	ret := _m.Called(ctx, repoID, email, token)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = rf(ctx, repoID, email, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTrackerSubscriptionWriter creates a new instance of TrackerSubscriptionWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackerSubscriptionWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackerSubscriptionWriter {
	mock := &TrackerSubscriptionWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
