// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TrackerSubscriptionDeleter is an autogenerated mock type for the TrackerSubscriptionDeleter type
type TrackerSubscriptionDeleter struct {
	mock.Mock
}

// DeleteByEmailAndRepo provides a mock function with given fields: ctx, email, repoName
func (_m *TrackerSubscriptionDeleter) DeleteByEmailAndRepo(ctx context.Context, email string, repoName string) error {
	ret := _m.Called(ctx, email, repoName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByEmailAndRepo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, repoName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByUserIDAndRepo provides a mock function with given fields: ctx, userID, repoName
func (_m *TrackerSubscriptionDeleter) DeleteByUserIDAndRepo(ctx context.Context, userID int64, repoName string) error {
	ret := _m.Called(ctx, userID, repoName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserIDAndRepo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, repoName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasSubscriptions provides a mock function with given fields: ctx, repoName
func (_m *TrackerSubscriptionDeleter) HasSubscriptions(ctx context.Context, repoName string) (bool, error) {
	ret := _m.Called(ctx, repoName)

	if len(ret) == 0 {
		panic("no return value specified for HasSubscriptions")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, repoName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, repoName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repoName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTrackerSubscriptionDeleter creates a new instance of TrackerSubscriptionDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackerSubscriptionDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackerSubscriptionDeleter {
	mock := &TrackerSubscriptionDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
