apiVersion: v1
kind: ConfigMap
metadata:
  name: subscription-config
data:
  SUBSCRIPTION_DB_MAX_OPEN_CONNS: "25"
  SUBSCRIPTION_DB_MIN_CONNS: "5"
  SUBSCRIPTION_DB_MAX_CONN_IDLE_TIME: "30m"
  SUBSCRIPTION_DB_HEALTH_CHECK_PERIOD: "1m"
  APP_HTTP_PORT: "8080"
  APP_GRPC_PORT: "9091"
  HTTP_SHUTDOWN_TIMEOUT: "5s"
  HTTP_REQUEST_TIMEOUT: "5s"
  APP_BASE_URL: "http://localhost:8080"
  RATE_LIMIT: "10-S"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  TRACKING_GRPC_ADDR: "tracking:50051"
