apiVersion: v1
kind: Secret
metadata:
  name: subscription-secret
type: Opaque
stringData:
  SUBSCRIPTION_DB_SOURCE: "postgres://ReilYehor:ReilYehor159951@postgres-subscription:5432/subscription_db?sslmode=disable"
  APP_API_KEY: "my-super-secret-token-123"
  REDIS_PASSWORD: "ReilYehor159951"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
