// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/tracking.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrCreateRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateRepositoryRequest) Reset() {
	*x = GetOrCreateRepositoryRequest{}
	mi := &file_v1_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateRepositoryRequest) ProtoMessage() {}

func (x *GetOrCreateRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateRepositoryRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_v1_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrCreateRepositoryRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type GetOrCreateRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateRepositoryResponse) Reset() {
	*x = GetOrCreateRepositoryResponse{}
	mi := &file_v1_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateRepositoryResponse) ProtoMessage() {}

func (x *GetOrCreateRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateRepositoryResponse.ProtoReflect.Descriptor instead.
func (*GetOrCreateRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_v1_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrCreateRepositoryResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrCreateRepositoryResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

var File_v1_tracking_proto protoreflect.FileDescriptor

const file_v1_tracking_proto_rawDesc = "" +
	"\n" +
	"\x11v1/tracking.proto\x12\vtracking.v1\";\n" +
	"\x1cGetOrCreateRepositoryRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\"L\n" +
	"\x1dGetOrCreateRepositoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName2\x81\x01\n" +
	"\x0fTrackingService\x12n\n" +
	"\x15GetOrCreateRepository\x12).tracking.v1.GetOrCreateRepositoryRequest\x1a*.tracking.v1.GetOrCreateRepositoryResponseBnZlgithub.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/infrastructure/grpc/proto/v1b\x06proto3"

var (
	file_v1_tracking_proto_rawDescOnce sync.Once
	file_v1_tracking_proto_rawDescData []byte
)

func file_v1_tracking_proto_rawDescGZIP() []byte {
	file_v1_tracking_proto_rawDescOnce.Do(func() {
		file_v1_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_tracking_proto_rawDesc), len(file_v1_tracking_proto_rawDesc)))
	})
	return file_v1_tracking_proto_rawDescData
}

var file_v1_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_tracking_proto_goTypes = []any{
	(*GetOrCreateRepositoryRequest)(nil),  // 0: tracking.v1.GetOrCreateRepositoryRequest
	(*GetOrCreateRepositoryResponse)(nil), // 1: tracking.v1.GetOrCreateRepositoryResponse
}
var file_v1_tracking_proto_depIdxs = []int32{
	0, // 0: tracking.v1.TrackingService.GetOrCreateRepository:input_type -> tracking.v1.GetOrCreateRepositoryRequest
	1, // 1: tracking.v1.TrackingService.GetOrCreateRepository:output_type -> tracking.v1.GetOrCreateRepositoryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_tracking_proto_init() }
func file_v1_tracking_proto_init() {
	if File_v1_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_tracking_proto_rawDesc), len(file_v1_tracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_tracking_proto_goTypes,
		DependencyIndexes: file_v1_tracking_proto_depIdxs,
		MessageInfos:      file_v1_tracking_proto_msgTypes,
	}.Build()
	File_v1_tracking_proto = out.File
	file_v1_tracking_proto_goTypes = nil
	file_v1_tracking_proto_depIdxs = nil
}
