// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	usecase2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/domain/usecase"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/infrastructure/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/infrastructure/clients/github"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/infrastructure/outbox"
	postgres2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/repository/postgres"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/usecase"
	rabbitmq2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/cache/redis"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/config"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/storage/postgres"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"time"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg Config) (*App, func(), error) {
	trackingDBConfig := ProvideTrackingDBConfig(cfg)
	poolConfig := ProvideTrackingPoolConfig(trackingDBConfig)
	pool, cleanup, err := postgres.New(ctx, poolConfig)
	if err != nil {
		return nil, nil, err
	}
	repositoryRepository := postgres2.NewRepositoryRepository(pool)
	gitHubConfig := ProvideGitHubConfig(cfg)
	gitHubClient := github.NewGitHubClient(gitHubConfig)
	redisConfig := ProvideRedisConfig(cfg)
	client, err := redis.NewRedisClient(redisConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache := redis.NewCache(client)
	serviceGitHubClient := ProvideCachedClient(gitHubClient, cache)
	repositoryUseCase := usecase.NewRepositoryUseCase(repositoryRepository, serviceGitHubClient)
	subscriptionRepository := postgres2.NewTrackerSubscriptionRepository(pool)
	rabbitMQConfig := ProvideRabbitMQConfig(cfg)
	connection, cleanup2, err := ProvideRabbitMQConnection(rabbitMQConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publisher, err := rabbitmq.NewPublisher(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcClientConfig := ProvideGRPCClientConfig(cfg)
	clientConn, cleanup3, err := ProvideSubscriptionGRPCConn(grpcClientConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tagUpdatedPublisher := ProvideTagUpdatedGRPCPublisher(clientConn, grpcClientConfig)
	outboxRepository := postgres2.NewOutboxRepository(pool)
	transactor := postgres.NewTransactor(pool)
	releaseProcessor := usecase.NewReleaseProcessor(repositoryRepository, repositoryUseCase, subscriptionRepository, publisher, tagUpdatedPublisher, outboxRepository, transactor)
	subscriptionActivatedConsumer := rabbitmq.NewSubscriptionActivatedConsumer(connection, repositoryUseCase, subscriptionRepository)
	unsubscriptionActivatedConsumer := rabbitmq.NewUnsubscriptionActivatedConsumer(connection, repositoryUseCase, subscriptionRepository)
	duration := ProvideOutboxInterval()
	relay := outbox.NewRelay(outboxRepository, connection, duration)
	app := &App{
		ReleaseProcessor:                releaseProcessor,
		SubscriptionActivatedConsumer:   subscriptionActivatedConsumer,
		UnsubscriptionActivatedConsumer: unsubscriptionActivatedConsumer,
		OutboxRelay:                     relay,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func ProvideTrackingDBConfig(cfg Config) config.TrackingDBConfig { return cfg.TrackingDB }

func ProvideRedisConfig(cfg Config) config.RedisConfig { return cfg.Redis }

func ProvideGitHubConfig(cfg Config) config.GitHubConfig { return cfg.GitHub }

func ProvideRabbitMQConfig(cfg Config) config.RabbitMQConfig { return cfg.RabbitMQ }

func ProvideGRPCClientConfig(cfg Config) config.GRPCClientConfig { return cfg.GRPCClient }

func ProvideRabbitMQConnection(cfg config.RabbitMQConfig) (*rabbitmq2.Connection, func(), error) {
	return rabbitmq2.NewConnection(cfg.URL)
}

func ProvideSubscriptionGRPCConn(cfg config.GRPCClientConfig) (*grpc.ClientConn, func(), error) {
	conn, err := grpc.NewClient(cfg.SubscriptionAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, nil, fmt.Errorf("dial subscription grpc: %w", err)
	}
	return conn, func() { conn.Close() }, nil
}

func ProvideOutboxInterval() time.Duration {
	return 5 * time.Second
}

type App struct {
	ReleaseProcessor                usecase2.ReleaseProcessorUseCase
	SubscriptionActivatedConsumer   *rabbitmq.SubscriptionActivatedConsumer
	UnsubscriptionActivatedConsumer *rabbitmq.UnsubscriptionActivatedConsumer
	OutboxRelay                     *outbox.Relay
}
