// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	usecase2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/domain/usecase"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/infrastructure/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/infrastructure/clients/github"
	postgres2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/repository/postgres"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/usecase"
	rabbitmq2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/cache/redis"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/config"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/storage/postgres"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg Config) (*App, func(), error) {
	trackingDBConfig := ProvideTrackingDBConfig(cfg)
	poolConfig := ProvideTrackingPoolConfig(trackingDBConfig)
	pool, cleanup, err := postgres.New(ctx, poolConfig)
	if err != nil {
		return nil, nil, err
	}
	repositoryRepository := postgres2.NewRepositoryRepository(pool)
	gitHubConfig := ProvideGitHubConfig(cfg)
	gitHubClient := github.NewGitHubClient(gitHubConfig)
	redisConfig := ProvideRedisConfig(cfg)
	client, err := redis.NewRedisClient(redisConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache := redis.NewCache(client)
	serviceGitHubClient := ProvideCachedClient(gitHubClient, cache)
	repositoryUseCase := usecase.NewRepositoryUseCase(repositoryRepository, serviceGitHubClient)
	subscriptionRepository := postgres2.NewTrackerSubscriptionRepository(pool)
	rabbitMQConfig := ProvideRabbitMQConfig(cfg)
	connection, cleanup2, err := ProvideRabbitMQConnection(rabbitMQConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publisher, err := rabbitmq.NewPublisher(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tagUpdatedPublisher, err := rabbitmq.NewTagUpdatedPublisher(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	releaseProcessor := usecase.NewReleaseProcessor(repositoryRepository, repositoryUseCase, subscriptionRepository, publisher, tagUpdatedPublisher)
	subscriptionActivatedConsumer := rabbitmq.NewSubscriptionActivatedConsumer(connection, repositoryUseCase, subscriptionRepository)
	unsubscriptionActivatedConsumer := rabbitmq.NewUnsubscriptionActivatedConsumer(connection, repositoryUseCase, subscriptionRepository)
	app := &App{
		ReleaseProcessor:                releaseProcessor,
		SubscriptionActivatedConsumer:   subscriptionActivatedConsumer,
		UnsubscriptionActivatedConsumer: unsubscriptionActivatedConsumer,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func ProvideTrackingDBConfig(cfg Config) config.TrackingDBConfig { return cfg.TrackingDB }

func ProvideRedisConfig(cfg Config) config.RedisConfig { return cfg.Redis }

func ProvideGitHubConfig(cfg Config) config.GitHubConfig { return cfg.GitHub }

func ProvideRabbitMQConfig(cfg Config) config.RabbitMQConfig { return cfg.RabbitMQ }

func ProvideRabbitMQConnection(cfg config.RabbitMQConfig) (*rabbitmq2.Connection, func(), error) {
	return rabbitmq2.NewConnection(cfg.URL)
}

type App struct {
	ReleaseProcessor                usecase2.ReleaseProcessorUseCase
	SubscriptionActivatedConsumer   *rabbitmq.SubscriptionActivatedConsumer
	UnsubscriptionActivatedConsumer *rabbitmq.UnsubscriptionActivatedConsumer
}
