// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	rabbitmq2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/shared/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/shared/cache/redis"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/shared/config"
	sharedcache "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/shared/domain/cache"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/shared/storage/postgres"
	repository2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/subscription/domain/repository"
	postgres3 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/subscription/repository/postgres"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/domain/port"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/domain/repository"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/domain/service"
	usecase2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/domain/usecase"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/infrastructure/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/infrastructure/clients/github"
	postgres2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/repository/postgres"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/usecase"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg Config) (*App, func(), error) {
	dbConfig := ProvideDBConfig(cfg)
	pool, cleanup, err := postgres.New(ctx, dbConfig)
	if err != nil {
		return nil, nil, err
	}
	repositoryRepository := postgres2.NewRepositoryRepository(pool)
	gitHubConfig := ProvideGitHubConfig(cfg)
	gitHubClient := github.NewGitHubClient(gitHubConfig)
	redisConfig := ProvideRedisConfig(cfg)
	client, err := redis.NewRedisClient(redisConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache := redis.NewCache(client)
	serviceGitHubClient := ProvideCachedClient(gitHubClient, cache)
	repositoryUseCase := usecase.NewRepositoryUseCase(repositoryRepository, serviceGitHubClient)
	subscriptionRepository := postgres3.NewSubscriptionRepository(pool)
	rabbitMQConfig := ProvideRabbitMQConfig(cfg)
	connection, cleanup2, err := ProvideRabbitMQConnection(rabbitMQConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publisher, err := rabbitmq.NewPublisher(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	releaseProcessor := usecase.NewReleaseProcessor(repositoryRepository, repositoryUseCase, subscriptionRepository, publisher)
	app := &App{
		ReleaseProcessor: releaseProcessor,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func ProvideDBConfig(cfg Config) config.DBConfig { return cfg.DB }

func ProvideRedisConfig(cfg Config) config.RedisConfig { return cfg.Redis }

func ProvideGitHubConfig(cfg Config) config.GitHubConfig { return cfg.GitHub }

func ProvideRabbitMQConfig(cfg Config) config.RabbitMQConfig { return cfg.RabbitMQ }

func ProvideRabbitMQConnection(cfg config.RabbitMQConfig) (*rabbitmq2.Connection, func(), error) {
	return rabbitmq2.NewConnection(cfg.URL)
}

func ProvideCachedClient(c *github.GitHubClient, cache sharedcache.Cache) service.GitHubClient {
	return github.NewCachedGitHubClient(c, cache)
}

var GitHubSet = wire.NewSet(github.NewGitHubClient, ProvideCachedClient)

var CacheSet = wire.NewSet(redis.NewRedisClient, redis.NewCache, wire.Bind(new(sharedcache.Cache), new(*redis.Cache)))

var RepositorySet = wire.NewSet(postgres.New, postgres2.NewRepositoryRepository, postgres3.NewSubscriptionRepository, wire.Bind(new(postgres.PgxInterface), new(*pgxpool.Pool)), wire.Bind(new(repository.RepositoryRepository), new(*postgres2.RepositoryRepository)), wire.Bind(new(repository2.SubscriptionRepository), new(*postgres3.SubscriptionRepository)), wire.Bind(new(port.RepositoryReader), new(*postgres2.RepositoryRepository)), wire.Bind(new(port.SubscriberReader), new(*postgres3.SubscriptionRepository)))

var BrokerSet = wire.NewSet(
	ProvideRabbitMQConnection, rabbitmq.NewPublisher, wire.Bind(new(port.NotificationPublisher), new(*rabbitmq.Publisher)),
)

var UseCaseSet = wire.NewSet(usecase.NewRepositoryUseCase, usecase.NewReleaseProcessor, wire.Bind(new(usecase2.RepositoryUseCase), new(*usecase.RepositoryUseCase)), wire.Bind(new(usecase2.ReleaseProcessorUseCase), new(*usecase.ReleaseProcessor)))

type App struct {
	ReleaseProcessor usecase2.ReleaseProcessorUseCase
}
