// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/subscription/infrastructure/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/subscription/infrastructure/outbox"
	postgres2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/subscription/repository/postgres"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/subscription/saga"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/subscription/transport/grpc"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/subscription/transport/http"
	usecase2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/subscription/usecase"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/infrastructure/clients/github"
	postgres3 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/repository/postgres"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/tracking/usecase"
	rabbitmq2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/cache/redis"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/config"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/storage/postgres"
	grpc2 "google.golang.org/grpc"
	"time"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg Config) (*App, func(), error) {
	subscriptionDBConfig := ProvideSubscriptionDBConfig(cfg)
	poolConfig := ProvideSubscriptionPoolConfig(subscriptionDBConfig)
	pool, cleanup, err := postgres.New(ctx, poolConfig)
	if err != nil {
		return nil, nil, err
	}
	subscriptionRepository := postgres2.NewSubscriptionRepository(pool)
	userRepository := postgres2.NewUserRepository(pool)
	repositoryRepository := postgres3.NewRepositoryRepository(pool)
	gitHubConfig := ProvideGitHubConfig(cfg)
	gitHubClient := github.NewGitHubClient(gitHubConfig)
	redisConfig := ProvideRedisConfig(cfg)
	client, err := redis.NewRedisClient(redisConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache := redis.NewCache(client)
	serviceGitHubClient := ProvideCachedClient(gitHubClient, cache)
	repositoryUseCase := usecase.NewRepositoryUseCase(repositoryRepository, serviceGitHubClient)
	sagaRepository := postgres2.NewSagaRepository(pool)
	outboxRepository := postgres2.NewOutboxRepository(pool)
	transactor := postgres.NewTransactor(pool)
	orchestrator := saga.NewOrchestrator(sagaRepository, subscriptionRepository, outboxRepository, transactor)
	userUseCase, cleanup2 := usecase2.NewUserUseCase(ctx, subscriptionRepository, userRepository, repositoryUseCase, orchestrator, transactor, outboxRepository)
	postgresRepositoryRepository := postgres2.NewRepositoryRepository(pool)
	usecaseRepositoryUseCase := usecase2.NewRepositoryUseCase(postgresRepositoryRepository)
	httpConfig := ProvideHTTPConfig(cfg)
	appConfig := ProvideAppConfig(cfg)
	ginServer := http.NewGinServer(userUseCase, usecaseRepositoryUseCase, client, httpConfig, appConfig)
	subscriptionHandler := grpc.NewSubscriptionHandler(userUseCase, usecaseRepositoryUseCase)
	server := grpc.NewGrpcServer(subscriptionHandler, appConfig)
	rabbitMQConfig := ProvideRabbitMQConfig(cfg)
	connection, cleanup3, err := ProvideRabbitMQConnection(rabbitMQConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sagaResultConsumer := rabbitmq.NewSagaResultConsumer(connection, orchestrator)
	duration := ProvideOutboxInterval()
	relay := outbox.NewRelay(outboxRepository, connection, duration)
	app := &App{
		HTTPServer:         ginServer,
		GrpcServer:         server,
		SagaResultConsumer: sagaResultConsumer,
		OutboxRelay:        relay,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func ProvideSubscriptionDBConfig(cfg Config) config.SubscriptionDBConfig { return cfg.SubscriptionDB }

func ProvideRedisConfig(cfg Config) config.RedisConfig { return cfg.Redis }

func ProvideGitHubConfig(cfg Config) config.GitHubConfig { return cfg.GitHub }

func ProvideHTTPConfig(cfg Config) config.HTTPConfig { return cfg.HTTP }

func ProvideAppConfig(cfg Config) config.AppConfig { return cfg.App }

func ProvideRabbitMQConfig(cfg Config) config.RabbitMQConfig { return cfg.RabbitMQ }

func ProvideRabbitMQConnection(cfg config.RabbitMQConfig) (*rabbitmq2.Connection, func(), error) {
	return rabbitmq2.NewConnection(cfg.URL)
}

func ProvideOutboxInterval() time.Duration {
	return 5 * time.Second
}

type App struct {
	HTTPServer         *http.GinServer
	GrpcServer         *grpc2.Server
	SagaResultConsumer *rabbitmq.SagaResultConsumer
	OutboxRelay        *outbox.Relay
}
