// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ConfirmationSender is an autogenerated mock type for the ConfirmationSender type
type ConfirmationSender struct {
	mock.Mock
}

// SendConfirmation provides a mock function with given fields: ctx, to, repoName, token, sagaID, subscriptionID
func (_m *ConfirmationSender) SendConfirmation(ctx context.Context, to string, repoName string, token string, sagaID int64, subscriptionID int64) error {
	ret := _m.Called(ctx, to, repoName, token, sagaID, subscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for SendConfirmation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, int64) error); ok {
		r0 = rf(ctx, to, repoName, token, sagaID, subscriptionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConfirmationSender creates a new instance of ConfirmationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfirmationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfirmationSender {
	mock := &ConfirmationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
