// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/config"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/domain/repository"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/domain/service"
	usecase2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/domain/usecase"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/infrastructure/cache/redis"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/infrastructure/clients/email"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/infrastructure/clients/github"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/infrastructure/storage/postgres"
	postgres2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/repository/postgres"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/transport/grpc"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/transport/http"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/usecase"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	grpc2 "google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg config.Config) (*App, func(), error) {
	dbConfig := ProvideDBConfig(cfg)
	pool, cleanup, err := postgres.New(ctx, dbConfig)
	if err != nil {
		return nil, nil, err
	}
	subscriptionRepository := postgres2.NewSubscriptionRepository(pool)
	userRepository := postgres2.NewUserRepository(pool)
	repositoryRepository := postgres2.NewRepositoryRepository(pool)
	gitHubConfig := ProvideGitHubConfig(cfg)
	gitHubClient := github.NewGitHubClient(gitHubConfig)
	redisConfig := ProvideRedisConfig(cfg)
	client, err := redis.NewRedisClient(redisConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache := redis.NewCache(client)
	serviceGitHubClient := ProvideCachedClient(gitHubClient, cache)
	repositoryUseCase := usecase.NewRepositoryUseCase(repositoryRepository, serviceGitHubClient)
	emailConfig := ProvideEmailConfig(cfg)
	smtpClient := email.NewSMTPClient(emailConfig)
	appConfig := ProvideAppConfig(cfg)
	string2 := ProvideBaseURL(appConfig)
	emailManager := email.NewEmailManager(smtpClient, string2)
	userUseCase := usecase.NewUserUseCase(ctx, subscriptionRepository, userRepository, repositoryUseCase, emailManager)
	httpConfig := ProvideHTTPConfig(cfg)
	ginServer := http.NewGinServer(userUseCase, client, httpConfig, appConfig)
	subscriptionHandler := grpc.NewSubscriptionHandler(userUseCase)
	server := grpc.NewGrpcServer(subscriptionHandler, appConfig)
	workerConfig := ProvideWorkerConfig(cfg)
	notificationUseCase := usecase.NewNotificationUseCase(subscriptionRepository, repositoryRepository, repositoryUseCase, emailManager, workerConfig)
	app := &App{
		HTTPServer:          ginServer,
		GrpcServer:          server,
		NotificationUseCase: notificationUseCase,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func ProvideDBConfig(cfg config.Config) config.DBConfig { return cfg.DB }

func ProvideRedisConfig(cfg config.Config) config.RedisConfig { return cfg.Redis }

func ProvideEmailConfig(cfg config.Config) config.EmailConfig { return cfg.Email }

func ProvideGitHubConfig(cfg config.Config) config.GitHubConfig { return cfg.GitHub }

func ProvideHTTPConfig(cfg config.Config) config.HTTPConfig { return cfg.HTTP }

func ProvideAppConfig(cfg config.Config) config.AppConfig { return cfg.App }

func ProvideWorkerConfig(cfg config.Config) config.WorkerConfig { return cfg.Worker }

func ProvideBaseURL(cfg config.AppConfig) string { return cfg.BaseURL }

var UseCaseSet = wire.NewSet(usecase.NewRepositoryUseCase, usecase.NewNotificationUseCase, usecase.NewUserUseCase, wire.Bind(new(usecase2.RepositoryUseCase), new(*usecase.RepositoryUseCase)), wire.Bind(new(usecase2.NotificationUseCase), new(*usecase.NotificationUseCase)), wire.Bind(new(usecase2.UserUseCase), new(*usecase.UserUseCase)))

var RepositorySet = wire.NewSet(postgres.New, postgres2.NewRepositoryRepository, postgres2.NewSubscriptionRepository, postgres2.NewUserRepository, wire.Bind(new(postgres2.PgxInterface), new(*pgxpool.Pool)), wire.Bind(new(repository.RepositoryRepository), new(*postgres2.RepositoryRepository)), wire.Bind(new(repository.SubscriptionRepository), new(*postgres2.SubscriptionRepository)), wire.Bind(new(repository.UserRepository), new(*postgres2.UserRepository)))

func ProvideCachedClient(
	c *github.GitHubClient,
	cache service.Cache,
) service.GitHubClient {
	return github.NewCachedGitHubClient(c, cache)
}

var GitHubSet = wire.NewSet(github.NewGitHubClient, ProvideCachedClient)

var RestSet = wire.NewSet(http.NewGinServer)

var CacheSet = wire.NewSet(redis.NewRedisClient, redis.NewCache, wire.Bind(new(service.Cache), new(*redis.Cache)))

var EmailSet = wire.NewSet(email.NewSMTPClient, email.NewEmailManager, wire.Bind(new(service.EmailService), new(*email.EmailManager)), wire.Bind(new(service.EmailSender), new(*email.SMTPClient)))

var ServicesSet = wire.NewSet(
	GitHubSet,
	EmailSet,
)

var GrpcSet = wire.NewSet(grpc.NewSubscriptionHandler, grpc.NewGrpcServer)

type App struct {
	HTTPServer          *http.GinServer
	GrpcServer          *grpc2.Server
	NotificationUseCase usecase2.NotificationUseCase
}
