// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/config"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/domain/repository"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/domain/service"
	usecase2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/domain/usecase"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/infrastructure/cache/redis"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/infrastructure/clients/email"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/infrastructure/clients/github"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/infrastructure/storage/postgres"
	postgres2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/repository/postgres"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/transport/grpc"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/transport/http"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/transport/http/handlers"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/usecase"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	grpc2 "google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, redisHost config.RedisHostType, redisPort config.RedisPortType, redisPassword config.RedisPasswordType, redisDB int, dsn config.DSNType, emailHost config.EmailHostType, emailPort config.EmailPortType, emailPassword config.EmailPasswordType, emailFrom config.EmailFromType, emailUser config.EmailUserType, apiKey config.APIKeyType, githubToken config.GitHubTokenType, baseURL config.AppBaseURLType) (*App, func(), error) {
	pool, cleanup, err := postgres.New(ctx, dsn)
	if err != nil {
		return nil, nil, err
	}
	subscriptionRepository := postgres2.NewSubscriptionRepository(pool)
	gitHubClient := github.NewGitHubClient(githubToken)
	client, err := redis.NewRedisClient(redisHost, redisPort, redisPassword, redisDB)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache := redis.NewCache(client)
	serviceGitHubClient := ProvideCachedClient(gitHubClient, cache)
	repositoryRepository := postgres2.NewRepositoryRepository(pool)
	repositoryUseCase := usecase.NewRepositoryUseCase(repositoryRepository, serviceGitHubClient)
	userRepository := postgres2.NewUserRepository(pool)
	smtpClient := email.NewSMTPClient(emailHost, emailPort, emailFrom, emailPassword, emailUser)
	emailManager := email.NewEmailManager(smtpClient, baseURL)
	subscriptionUseCase := usecase.NewSubscriptionUseCase(subscriptionRepository, serviceGitHubClient, repositoryUseCase, userRepository, emailManager, repositoryRepository)
	ginServer := http.NewGinServer(subscriptionUseCase, client, apiKey)
	subscriptionHandler := grpc.NewSubscriptionHandler(subscriptionUseCase)
	server := grpc.NewGrpcServer(subscriptionHandler, apiKey)
	app := &App{
		HTTPServer:          ginServer,
		GrpcServer:          server,
		SubscriptionUseCase: subscriptionUseCase,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var UseCaseSet = wire.NewSet(usecase.NewSubscriptionUseCase, usecase.NewRepositoryUseCase, wire.Bind(new(usecase2.SubscriptionUseCase), new(*usecase.SubscriptionUseCase)), wire.Bind(new(usecase2.RepositoryUseCase), new(*usecase.RepositoryUseCase)))

var RepositorySet = wire.NewSet(postgres.New, postgres2.NewRepositoryRepository, postgres2.NewSubscriptionRepository, postgres2.NewUserRepository, wire.Bind(new(postgres2.PgxInterface), new(*pgxpool.Pool)), wire.Bind(new(repository.RepositoryRepository), new(*postgres2.RepositoryRepository)), wire.Bind(new(repository.SubscriptionRepository), new(*postgres2.SubscriptionRepository)), wire.Bind(new(repository.UserRepository), new(*postgres2.UserRepository)))

func ProvideCachedClient(c *github.GitHubClient, cache service.Cache) service.GitHubClient {
	return github.NewCachedGitHubClient(c, cache)
}

var GitHubSet = wire.NewSet(github.NewGitHubClient, ProvideCachedClient)

var RestSet = wire.NewSet(http.NewGinServer, handlers.NewHandler)

var CacheSet = wire.NewSet(redis.NewRedisClient, redis.NewCache, wire.Bind(new(service.Cache), new(*redis.Cache)))

var EmailSet = wire.NewSet(email.NewSMTPClient, email.NewEmailManager, wire.Bind(new(service.EmailService), new(*email.EmailManager)), wire.Bind(new(service.EmailSender), new(*email.SMTPClient)))

var ServicesSet = wire.NewSet(
	GitHubSet,
	EmailSet,
)

var GrpcSet = wire.NewSet(grpc.NewSubscriptionHandler, grpc.NewGrpcServer)

type App struct {
	HTTPServer          *http.GinServer
	GrpcServer          *grpc2.Server
	SubscriptionUseCase usecase2.SubscriptionUseCase
}
