// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	usecase2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/tracking/internal/domain/usecase"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/tracking/internal/infrastructure/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/tracking/internal/infrastructure/clients/github"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/tracking/internal/infrastructure/outbox"
	postgres2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/tracking/internal/repository/postgres"
	rabbitmq2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/tracking/internal/transport/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/tracking/internal/transport/grpc"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/tracking/internal/usecase"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/config"
	rabbitmq3 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/infrastructure/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/infrastructure/cache/redis"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/infrastructure/storage/postgres"
	grpc2 "google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"net/http"
	"time"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg Config) (*App, func(), error) {
	trackingDBConfig := ProvideTrackingDBConfig(cfg)
	poolConfig := ProvideTrackingPoolConfig(trackingDBConfig)
	pool, cleanup, err := postgres.New(ctx, poolConfig)
	if err != nil {
		return nil, nil, err
	}
	repositoryRepository := postgres2.NewRepositoryRepository(pool)
	gitHubConfig := ProvideGitHubConfig(cfg)
	gitHubClient := github.NewGitHubClient(gitHubConfig)
	redisConfig := ProvideRedisConfig(cfg)
	client, err := redis.NewRedisClient(redisConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache := redis.NewCache(client)
	serviceGitHubClient := ProvideCachedClient(gitHubClient, cache)
	repositoryUseCase := usecase.NewRepositoryUseCase(repositoryRepository, serviceGitHubClient)
	trackingHandler := grpc.NewTrackingHandler(repositoryUseCase)
	appConfig := ProvideAppConfig(cfg)
	server := grpc.NewGrpcServer(trackingHandler, appConfig)
	subscriptionRepository := postgres2.NewTrackerSubscriptionRepository(pool)
	rabbitMQConfig := ProvideRabbitMQConfig(cfg)
	connection, cleanup2, err := ProvideRabbitMQConnection(rabbitMQConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publisher, err := rabbitmq.NewPublisher(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	subscriptionClientConfig := ProvideSubscriptionClientConfig(cfg)
	clientConn, cleanup3, err := ProvideSubscriptionGRPCConn(subscriptionClientConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tagUpdatedPublisher := ProvideTagUpdatedGRPCPublisher(clientConn, subscriptionClientConfig)
	httpClient := ProvideHTTPClient()
	httpTagUpdatedPublisher := ProvideTagUpdatedHTTPPublisher(httpClient, subscriptionClientConfig)
	usecaseTagUpdatedPublisher := ProvideTagUpdatedPublisher(subscriptionClientConfig, tagUpdatedPublisher, httpTagUpdatedPublisher)
	outboxRepository := postgres2.NewOutboxRepository(pool)
	transactor := postgres.NewTransactor(pool)
	releaseProcessor := usecase.NewReleaseProcessor(repositoryRepository, repositoryUseCase, subscriptionRepository, publisher, usecaseTagUpdatedPublisher, outboxRepository, transactor)
	subscriptionActivatedConsumer := rabbitmq2.NewSubscriptionActivatedConsumer(connection, repositoryUseCase, subscriptionRepository)
	unsubscriptionActivatedConsumer := rabbitmq2.NewUnsubscriptionActivatedConsumer(connection, repositoryUseCase, subscriptionRepository)
	duration := ProvideOutboxInterval()
	relay := outbox.NewRelay(outboxRepository, connection, duration, transactor)
	app := &App{
		GrpcServer:                      server,
		ReleaseProcessor:                releaseProcessor,
		SubscriptionActivatedConsumer:   subscriptionActivatedConsumer,
		UnsubscriptionActivatedConsumer: unsubscriptionActivatedConsumer,
		OutboxRelay:                     relay,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func ProvideTrackingDBConfig(cfg Config) config.TrackingDBConfig { return cfg.TrackingDB }

func ProvideRedisConfig(cfg Config) config.RedisConfig { return cfg.Redis }

func ProvideGitHubConfig(cfg Config) config.GitHubConfig { return cfg.GitHub }

func ProvideRabbitMQConfig(cfg Config) config.RabbitMQConfig { return cfg.RabbitMQ }

func ProvideAppConfig(cfg Config) config.AppConfig { return cfg.App }

func ProvideSubscriptionClientConfig(cfg Config) config.SubscriptionClientConfig {
	return cfg.SubscriptionClient
}

func ProvideRabbitMQConnection(cfg config.RabbitMQConfig) (*rabbitmq3.Connection, func(), error) {
	return rabbitmq3.NewConnection(cfg.URL)
}

func ProvideSubscriptionGRPCConn(cfg config.SubscriptionClientConfig) (*grpc2.ClientConn, func(), error) {
	conn, err := grpc2.NewClient(cfg.SubscriptionGRPCAddr, grpc2.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, nil, fmt.Errorf("dial subscription grpc: %w", err)
	}
	return conn, func() { conn.Close() }, nil
}

func ProvideHTTPClient() *http.Client {
	return &http.Client{Timeout: 10 * time.Second}
}

func ProvideOutboxInterval() time.Duration {
	return 5 * time.Second
}

type App struct {
	GrpcServer                      *grpc2.Server
	ReleaseProcessor                usecase2.ReleaseProcessorUseCase
	SubscriptionActivatedConsumer   *rabbitmq2.SubscriptionActivatedConsumer
	UnsubscriptionActivatedConsumer *rabbitmq2.UnsubscriptionActivatedConsumer
	OutboxRelay                     *outbox.Relay
}
