// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/tracking/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryWriter is an autogenerated mock type for the RepositoryWriter type
type RepositoryWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, repo
func (_m *RepositoryWriter) Create(ctx context.Context, repo *model.Repository) error {
	ret := _m.Called(ctx, repo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Repository) error); ok {
		r0 = rf(ctx, repo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, name
func (_m *RepositoryWriter) Delete(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, repo
func (_m *RepositoryWriter) Update(ctx context.Context, repo *model.Repository) error {
	ret := _m.Called(ctx, repo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Repository) error); ok {
		r0 = rf(ctx, repo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepositoryWriter creates a new instance of RepositoryWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryWriter {
	mock := &RepositoryWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
