// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/services/tracking/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// SubscriberReader is an autogenerated mock type for the SubscriberReader type
type SubscriberReader struct {
	mock.Mock
}

// GetByRepoID provides a mock function with given fields: ctx, repoID
func (_m *SubscriberReader) GetByRepoID(ctx context.Context, repoID int64) ([]model.Subscriber, error) {
	ret := _m.Called(ctx, repoID)

	if len(ret) == 0 {
		panic("no return value specified for GetByRepoID")
	}

	var r0 []model.Subscriber
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Subscriber, error)); ok {
		return rf(ctx, repoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Subscriber); ok {
		r0 = rf(ctx, repoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscriber)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, repoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSubscriberReader creates a new instance of SubscriberReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriberReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriberReader {
	mock := &SubscriberReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
