// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/confirm/{token}": {
            "get": {
                "description": "Confirm a pending subscription using the token sent via email. This route is public (no API key) since it is reached from an email link.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Confirm email subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Confirmation token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "subscription confirmed successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Token is required",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscribe": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a pending subscription and send a confirmation email. Requires an API key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Subscribe to a repository",
                "parameters": [
                    {
                        "description": "Subscription details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.CreateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.CreateSubscriptionResponse"
                        }
                    },
                    "400": {
                        "description": "Malformed JSON body, or email/repository failed validation",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Repository not found on GitHub",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Unexpected internal error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "GitHub API is currently unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a list of all subscriptions (confirmed and pending) for a given email. Requires an API key.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Get all subscriptions by email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email address",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ListSubscriptionsResponse"
                        }
                    },
                    "400": {
                        "description": "Email query param is missing or not a valid email address",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/unsubscribe/{token}": {
            "get": {
                "description": "Remove a subscription using the one-time token from the unsubscribe link. This route is public (no API key) since it is reached from an email link.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Unsubscribe via token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unsubscribe token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "You have been successfully unsubscribed",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Token is required",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.CreateSubscriptionRequest": {
            "type": "object",
            "required": [
                "email",
                "repository"
            ],
            "properties": {
                "email": {
                    "description": "User email address for notifications.",
                    "type": "string",
                    "example": "user@example.com"
                },
                "repository": {
                    "description": "GitHub repository full name (owner/repo).",
                    "type": "string",
                    "example": "golang/go"
                }
            }
        },
        "github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.CreateSubscriptionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Status message indicating the result of the subscription creation.",
                    "type": "string",
                    "example": "Confirmation email sent"
                }
            }
        },
        "github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Human-readable error message.",
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        },
        "github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ListSubscriptionsResponse": {
            "type": "object",
            "properties": {
                "subscriptions": {
                    "description": "List of the user's subscriptions.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.SubscriptionResponse"
                    }
                },
                "total": {
                    "description": "Good practice to return count.",
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Human-readable status message.",
                    "type": "string",
                    "example": "subscription confirmed successfully"
                }
            }
        },
        "github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.SubscriptionResponse": {
            "type": "object",
            "properties": {
                "confirmed": {
                    "description": "Indicates whether the subscription has been confirmed by the user.",
                    "type": "boolean"
                },
                "created_at": {
                    "description": "Timestamp when the subscription was created.",
                    "type": "string",
                    "example": "2026-04-08T18:00:00Z"
                },
                "email": {
                    "description": "Subscriber's email address.",
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "description": "Unique identifier of the subscription.",
                    "type": "integer",
                    "example": 1
                },
                "last_seen_tag": {
                    "description": "The latest tag seen for this subscription, useful for tracking updates.",
                    "type": "string"
                },
                "repository_name": {
                    "description": "The name of the repository (extracted from FullName).",
                    "type": "string",
                    "example": "golang/go"
                }
            }
        },
        "github_com_GenesisEducationKyiv_software-engineering-school-6-0-ReilEgor_services_subscription_internal_transport_http_dto.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "description": "List of validation failure messages.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "invalid email format",
                        "invalid repository format (expected 'owner/repo')"
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "RepoNotifier API",
	Description:      "Subscription service: manages email subscriptions to GitHub repositories and notifies subscribers about new releases.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
