// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryUpdater is an autogenerated mock type for the RepositoryUpdater type
type RepositoryUpdater struct {
	mock.Mock
}

// UpdateTag provides a mock function with given fields: ctx, fullName, tag
func (_m *RepositoryUpdater) UpdateTag(ctx context.Context, fullName string, tag string) error {
	ret := _m.Called(ctx, fullName, tag)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, fullName, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepositoryUpdater creates a new instance of RepositoryUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryUpdater {
	mock := &RepositoryUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
