// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SagaOrchestrator is an autogenerated mock type for the SagaOrchestrator type
type SagaOrchestrator struct {
	mock.Mock
}

// Start provides a mock function with given fields: ctx, subscriptionID, email, repoName, token
func (_m *SagaOrchestrator) Start(ctx context.Context, subscriptionID int64, email string, repoName string, token string) error {
	ret := _m.Called(ctx, subscriptionID, email, repoName, token)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string) error); ok {
		r0 = rf(ctx, subscriptionID, email, repoName, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSagaOrchestrator creates a new instance of SagaOrchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSagaOrchestrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *SagaOrchestrator {
	mock := &SagaOrchestrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
