// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/shared/config"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg Config) (*App, func(), error) {
	app := &App{}
	return app, func() {
	}, nil
}

// wire.go:

func ProvideEmailConfig(cfg Config) config.EmailConfig { return cfg.Email }

type App struct {
}
