// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/notification/infrastructure/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/notification/infrastructure/clients/email"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/internal/notification/usecase"
	rabbitmq2 "github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/broker/rabbitmq"
	"github.com/GenesisEducationKyiv/software-engineering-school-6-0-ReilEgor/shared/config"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg Config) (*App, func(), error) {
	rabbitMQConfig := ProvideRabbitMQConfig(cfg)
	connection, cleanup, err := ProvideRabbitMQConnection(rabbitMQConfig)
	if err != nil {
		return nil, nil, err
	}
	emailConfig := ProvideEmailConfig(cfg)
	smtpClient := email.NewSMTPClient(emailConfig)
	emailService := ProvideEmailService(smtpClient, cfg)
	notificationUseCase := usecase.NewNotificationUseCase(emailService)
	senderConfig := ProvideSenderConfig(cfg)
	duration := ProvideSendTimeout(senderConfig)
	notificationConsumer := rabbitmq.NewNotificationConsumer(connection, notificationUseCase, duration)
	sagaResultPublisher, err := rabbitmq.NewSagaResultPublisher(connection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	confirmationConsumer := rabbitmq.NewConfirmationConsumer(connection, emailService, duration, sagaResultPublisher)
	app := &App{
		NotificationConsumer: notificationConsumer,
		ConfirmationConsumer: confirmationConsumer,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func ProvideEmailConfig(cfg Config) config.EmailConfig { return cfg.Email }

func ProvideSenderConfig(cfg Config) config.SenderConfig { return cfg.Sender }

func ProvideRabbitMQConfig(cfg Config) config.RabbitMQConfig { return cfg.RabbitMQ }

func ProvideRabbitMQConnection(cfg config.RabbitMQConfig) (*rabbitmq2.Connection, func(), error) {
	return rabbitmq2.NewConnection(cfg.URL)
}

type App struct {
	NotificationConsumer *rabbitmq.NotificationConsumer
	ConfirmationConsumer *rabbitmq.ConfirmationConsumer
}
